Feature/tuf repositoty
openlawlibrary/taf pull request #561
Opened 2024-10-29 02:24 UTC by renatav

## Description (e.g. "Related to ...", etc.)

_Please replace this description with a concise description of this Pull Request._

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/taf/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/

2024-12-17 18:03 UTC, n-dusan requested changes
You've done a really great job with this PR. The amount of organization and work are impressive!

As for next steps, I'll be reviewing the tests and testing framework in more depth with @sale3. For now, I've left a handful of mostly non-substantial comments that you can take a look at.

2024-12-18 23:41 UTC, renatav commented on taf/tuf/repository.py
> +        Defined delegated paths of delegate target role or * in case of targets
The main targets role is simply a catch-all. This is an old string, but I can update it

2024-12-18 23:43 UTC, renatav commented on taf/tuf/keys.py
> +    return CryptoSigner(priv, _from_crypto(pub))
This is not even used, I'll remove it

2024-12-19 19:50 UTC, renatav commented on docs/developers/repository-classes.md
> +files inside the `targets` folder are tracked and secured by TUF.
To me, just TUF makes more sense. Storing hashes and lengths of target files in signed metadata files is what TUF does.

2024-12-19 19:51 UTC, renatav commented on taf/api/api_workflow.py
> +        raise
There is not reason why we wouldn't want to import anything from the api package imo

2024-12-20 20:50 UTC, renatav commented on taf/tests/tuf/test_create_edit_repo/conftest.py
> +    return full_path
That looks like an old comment that was moved here, I'll remove it

2024-12-20 21:00 UTC, renatav commented on taf/tuf/repository.py
> +        return signed_obj.delegations.roles
I added docstrings to all methods. Some are more detailed than others, but it still took a couple of hours. Let me know if any of them require a more detailed explanation.

2024-12-20 21:34 UTC, renatav commented on taf/auth_repo.py
> +            return [str(Path(target_path).as_posix()) for target_path in repositories]
It looks like this is no longer being used. I'll remove it

2024-12-20 21:37 UTC, renatav commented on taf/tuf/repository.py
> +    def update_snapshot_and_tiemstamp(self, signers_dict: Dict[str, List[CryptoSigner]]):
I can't find any occurrences of `update_snapshot_and_tiemstamp`, so I must have resolved this

2024-12-20 21:39 UTC, renatav commented on taf/api/roles.py
> +    parent_role_obj = auth_repo._role_obj(parent_role, auth_repo)
`remove_role` should be reimplemented fully. I couldn't find this this function call in the newest version.

2024-12-20 21:41 UTC, renatav commented on taf/keys.py
> +                signer = load_signer_from_private_keystore(
It raises `KeystoreError`, checked

2024-12-20 22:28 UTC, renatav commented on taf/tuf/repository.py
> +            pass
"If I remember correctly, a metadata file may not exist at some revisions, such as the initial commit.

2024-12-20 22:31 UTC, renatav commented on taf/tests/tuf/test_create_edit_repo/test_keys.py
> +    assert tuf_repo.snapshot().version == 2
I think this is also based on an older version of that test, I can't find this code

2024-12-20 22:54 UTC, renatav commented on taf/tuf/repository.py
> +        # if we only have a
Removed

2024-12-20 23:01 UTC, renatav commented on taf/git.py
> +        self._git(f"restore {' '.join(subdirectories)}")
I don't mind implementing this using something different or asking the user's to update their version of git (v2.23 was released over 5 years ago, so I'd assume that everyone on our team at least has a newer version). Would it be okay to update this in a separate PR?

2024-12-20 23:18 UTC, renatav commented on taf/tuf/storage.py
> +    def get(self, filepath: str):
I added some comments

2024-12-20 23:19 UTC, renatav commented on taf/tuf/storage.py
> +
Added a comment

2024-12-21 01:08 UTC, renatav commented
@n-dusan I updated the docstrings and addressed other commits

2024-12-23 10:20 UTC, n-dusan reviewed
I've just finished reviewing the testing framework and added 14 new CLI tests. 4 are currently failing. Could you take a look when you have a moment? I’m happy to help troubleshoot together if you’d like. I’ll push my commit to your branch so you can see the changes. Once those tests are passing, we can merge the PR. Also, your docstrings are fantastic. They really improve the code’s readability. 

After merging, I’ll focus on updating the platform to the latest TAF.

2024-12-23 10:20 UTC, n-dusan commented on taf/api/roles.py
> +    parent_role_obj = auth_repo._role_obj(parent_role, auth_repo)
Makes sense. Do we create an issue?

2024-12-23 10:20 UTC, n-dusan commented on taf/git.py
> +        self._git(f"restore {' '.join(subdirectories)}")
Yes

2024-12-23 10:23 UTC, n-dusan commented
By the way, should we consider doing a minor release of the current TAF changes off master before merging this PR? It's a big rewrite, so having a stable release in place might be a good idea

2024-12-23 19:04 UTC, renatav commented on taf/tests/test_api/test_roles.py
> +# def test_remove_role_when_no_targets(auth_repo_with_delegations: AuthenticationRepository, roles_keystore: str):
Sure, I'll create one

2024-12-24 03:14 UTC, renatav commented
@n-dusan Updated the tests and merge master. Ready for another review

2025-01-13 17:01 UTC, n-dusan approved these changes
Looks great, ready to merge!

2025-01-13 17:10 UTC, merged